In [93]:
import numpy as np
import pandas as pd
emotion = pd.read_csv("../data/各品类每日代理指数.csv",encoding='utf-8',index_col='销售日期')
emotion_pre = pd.read_csv("../data/代理指数未来一周预测.csv",encoding='utf-8',index_col='销售日期')
volume = pd.read_csv("../data/销售量按日期品类合并.csv",encoding='utf-8',index_col='销售日期')

In [94]:
print(emotion)
print(emotion_pre)
print(volume)

                 花叶类       花菜类     水生根茎类        茄类       辣椒类       食用菌
销售日期                                                                  
2020/7/1   19.175897  0.236495 -4.132788  0.921461 -0.622134  3.170321
2020/7/2   13.786113 -0.092394 -4.302012  0.710043 -1.073785  3.752385
2020/7/3   15.094849 -0.381225 -8.270809  0.946354 -1.561290  3.204998
2020/7/4   23.632755  0.630052 -3.364830  2.262836 -1.936748  3.723344
2020/7/5   11.632874  0.592140 -4.056903  4.148243 -2.509096  3.399236
...              ...       ...       ...       ...       ...       ...
2023/6/26  -5.915219 -0.500844 -2.228535 -0.006156  1.067913 -2.570690
2023/6/27 -16.666987 -0.175046 -3.735040 -1.069169  0.341080 -0.904200
2023/6/28 -16.117267 -0.260929 -2.462747 -0.601177  0.856726 -1.691719
2023/6/29 -16.567488 -0.265094 -3.191248 -0.748712  0.968036 -1.093431
2023/6/30 -16.936474 -0.204560 -3.480284 -0.740408  0.502294 -0.832791

[1095 rows x 6 columns]
                  花叶类       花菜类     水生根茎类        茄类 

In [95]:
emotion_merged = pd.concat([emotion,emotion_pre])
print(emotion_merged)

                  花叶类       花菜类     水生根茎类        茄类       辣椒类       食用菌
销售日期                                                                   
2020/7/1    19.175897  0.236495 -4.132788  0.921461 -0.622134  3.170321
2020/7/2    13.786113 -0.092394 -4.302012  0.710043 -1.073785  3.752385
2020/7/3    15.094849 -0.381225 -8.270809  0.946354 -1.561290  3.204998
2020/7/4    23.632755  0.630052 -3.364830  2.262836 -1.936748  3.723344
2020/7/5    11.632874  0.592140 -4.056903  4.148243 -2.509096  3.399236
...               ...       ...       ...       ...       ...       ...
2023-07-03 -12.465587  0.039220 -3.003270 -0.178633  0.616472 -1.602079
2023-07-04 -11.321983  0.047609 -3.007060 -0.093229  0.610381 -1.547500
2023-07-05 -10.313246  0.049462 -2.975877 -0.034990  0.613428 -1.511907
2023-07-06  -9.421203  0.048686 -2.909424  0.004238  0.609541 -1.616889
2023-07-07  -8.630285  0.046898 -2.858253  0.030184  0.604866 -1.650780

[1102 rows x 6 columns]


In [96]:
from sklearn.preprocessing import MinMaxScaler

In [97]:
emotion_ans = pd.DataFrame([])
emotion_ans['销售日期']=pd.date_range(start='2020-07-01', end='2023-07-07', freq='D')
emotion_ans = emotion_ans.set_index('销售日期')
volume_ans = pd.DataFrame([])
volume_ans['销售日期']=pd.date_range(start='2020-07-01', end='2023-06-30', freq='D')
volume_ans = volume_ans.set_index('销售日期')
for types in ['花叶类', '花菜类', '水生根茎类', '茄类', '辣椒类', '食用菌']:
    scaler = MinMaxScaler(feature_range=(0, 1))
    emotion_temp = pd.DataFrame([])
    emotion_temp['销售日期']=pd.date_range(start='2020-07-01', end='2023-07-07', freq='D')
    emotion_temp = emotion_temp.set_index('销售日期')
    emotion_temp[types] = emotion_merged[types].values
    emotion_temp = scaler.fit_transform(emotion_temp)
    #print(emotion_temp)
    emotion_ans[types] = emotion_temp

    volume_temp = pd.DataFrame([])
    volume_temp['销售日期'] = pd.date_range(start='2020-07-01', end='2023-06-30', freq='D')
    volume_temp = volume_temp.set_index('销售日期')
    volume_temp[types] = volume[types].values
    scaler1 = MinMaxScaler(feature_range=(0, 1))
    volume_temp = scaler1.fit_transform(volume_temp)
    #print(volume_temp)
    volume_ans[types] = volume_temp

    emotion_temp = scaler1.inverse_transform(emotion_temp)

    print(emotion_temp)
emotion_ans.to_csv('../data/emotion/情绪指数01映射.csv',sep=',',encoding='utf_8_sig')
volume_ans.to_csv('../data/emotion/销售量01映射.csv',sep=',',encoding='utf_8_sig')

[[890.49662556]
 [847.60869019]
 [858.02264971]
 ...
 [655.84372548]
 [662.94194827]
 [669.23549291]]
[[48.48258829]
 [44.93349919]
 [41.81667004]
 ...
 [46.46428726]
 [46.45591044]
 [46.43661469]]
[[49.99131231]
 [48.04452867]
 [ 2.3867776 ]
 ...
 [63.30062765]
 [64.06511438]
 [64.65378576]]
[[81.69616735]
 [80.568935  ]
 [81.82889187]
 ...
 [76.59658771]
 [76.80574142]
 [76.94407947]]
[[282.45572286]
 [272.28310458]
 [261.30294401]
 ...
 [310.28452711]
 [310.19697432]
 [310.09167613]]
[[212.14671608]
 [217.22348615]
 [212.4491742 ]
 ...
 [171.30827556]
 [170.39262016]
 [170.09702527]]


PermissionError: [Errno 13] Permission denied: '../data/emotion/情绪指数01映射.csv'